# packages in environment at C:\Users\KrayZ\miniconda3\envs\tf-gpu:
#
# Name                    Version                   Build  Channel
absl-py                   2.1.0                    pypi_0    pypi
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3                    pypi_0    pypi
ca-certificates           2024.7.4             h56e8100_0    conda-forge
cachetools                5.3.3                    pypi_0    pypi
certifi                   2024.7.4                 pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
cudatoolkit               11.2.2              h7d7167e_13    conda-forge
cudnn                     8.1.0.77             h3e0f4f4_0    conda-forge
debugpy                   1.8.2            py39ha51f57c_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
flatbuffers               24.3.25                  pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
google-auth               2.31.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.64.1                   pypi_0    pypi
h5py                      3.11.0                   pypi_0    pypi
idna                      3.7                      pypi_0    pypi
importlib-metadata        8.0.0              pyha770c72_0    conda-forge
importlib_metadata        8.0.0                hd8ed1ab_0    conda-forge
intel-openmp              2024.2.0           h57928b3_979    conda-forge
ipykernel                 6.29.5             pyh4bbf305_0    conda-forge
ipython                   8.18.1             pyh7428d3b_3    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.2              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2            py39hcbf5309_0    conda-forge
keras                     2.10.0                   pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
krb5                      1.21.3               hdf4eb48_0    conda-forge
libblas                   3.9.0              22_win64_mkl    conda-forge
libcblas                  3.9.0              22_win64_mkl    conda-forge
libclang                  18.1.1                   pypi_0    pypi
libhwloc                  2.11.0          default_h8125262_1000    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
liblapack                 3.9.0              22_win64_mkl    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libxml2                   2.12.7               h283a6d9_1    conda-forge
libzlib                   1.3.1                h2466b09_1    conda-forge
markdown                  3.6                      pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mkl                       2024.1.0           h66d3029_692    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
numpy                     1.26.4                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
openssl                   3.3.1                h2466b09_1    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2            py39h2366fc2_1    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       24.0             py39haa95532_0  
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.47             pyha770c72_0    conda-forge
protobuf                  3.19.6                   pypi_0    pypi
psutil                    6.0.0            py39ha55e580_0    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyasn1                    0.6.0                    pypi_0    pypi
pyasn1-modules            0.4.0                    pypi_0    pypi
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
python                    3.9.19               h1aa4202_1  
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pywin32                   306              py39h99910a6_2    conda-forge
pyzmq                     26.0.3           py39h03e5c00_0    conda-forge
requests                  2.32.3                   pypi_0    pypi
requests-oauthlib         2.0.0                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-learn              1.5.1            py39hdd013cc_0    conda-forge
scipy                     1.13.1           py39h1a10956_0    conda-forge
setuptools                69.5.1           py39haa95532_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.45.3               h2bbff1b_0  
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
tbb                       2021.12.0            hc790b64_2    conda-forge
tensorboard               2.10.1                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.10.1                   pypi_0    pypi
tensorflow-estimator      2.10.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.31.0                   pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
tornado                   6.4.1            py39ha55e580_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024a                h04d1e81_0  
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   2.2.2                    pypi_0    pypi
vc                        14.2                 h2eaa2aa_4  
vc14_runtime              14.40.33810         ha82c5b3_20    conda-forge
vs2015_runtime            14.40.33810         h3bf8584_20    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
werkzeug                  3.0.3                    pypi_0    pypi
wheel                     0.43.0           py39haa95532_0  
wrapt                     1.16.0                   pypi_0    pypi
zeromq                    4.3.5                he1f189c_4    conda-forge
zipp                      3.19.2             pyhd8ed1ab_0    conda-forge
